name: section_management
description: A Flutter application for managing sections.
version: 1.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqlite3_flutter_libs: ^0.5.18
  sqlite3: ^2.4.5
  path_provider: ^2.1.3
  path: ^1.9.0
  intl: any
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.1
  persian_datetime_picker: ^3.1.0
  bitsdojo_window: ^0.1.6
  file_picker: ^10.3.2
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  inno_bundle: ^0.11.2

flutter:
  uses-material-design: true

  assets:
    - assets/img/
inno_bundle:
  id: c8b17110-8901-11f0-b1a7-15e9e8c481ec
  publisher: Abbas Ghasemi